name:                xmonad-themes
version:             0.1.0.0
github:              "CyberGsus/xmonad-themes"
license:             MIT
author:              "Cyber Gsus"
maintainer:          "cyber.gsuscode@gmail.com"
copyright:           "2021 Cyber Gsus"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CyberGsus/xmonad-themes#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- directory
- filepath
- transformers
- mtl
- bytestring
- containers
- unordered-containers
- vector

library:
  source-dirs: src

tests:
  xmonad-themes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-themes
    - hspec
    - hspec-contrib
